### ISSUE TITLE
Not working with dinamically added DOM elements

### ISSUE THREAD

**Issue by AndreyMyagkov** [nsmdnl/css-container-queries#9]
Not working with dinamically added DOM elements.

You need to add reinitialization on MutationObserver.

**Comment by nsmdnl** [comment]
Hey, thank you for pointing it out.

I'm working on it and will keep you updated in this issue :)

**Comment by nsmdnl** [comment]
Hey @AndreyMyagkov 👋🏼  I hopefully fixed the issue you mentioned. Can you confirm that this now works on dynamically added DOM elements in your project?

Thanks in advance!
